name: 'Hello World'
description: 'my helloworld demo'
inputs:
  who_say_hello:
    description: 'who_say_hello'
    required: true
    default: 'cycle'
runs:
  using: "composite"
  steps:
    - run: |
      echo 'this is ok'
      echo ${{ inputs.who_say_hello }} helloworld

    shell: bash

    # - run: echo ${{ inputs.who_say_hello }} helloworld
    #   shell: bash