name: 'Hello World'
description: 'my helloworld demo'
inputs:
  who_say_hello:
    description: 'who_say_hello'
    required: true
    default: 'cycle'
  # ref:
  #   description: 'ref'
  #   required: true
  #   default: 'main'
  # sshkey:
  #   description: 'sshkey'
  #   required: true
  # user/email:
  #   description: 'user/email'
  #   required: true
runs:
  using: "composite"
  steps:
    # - run: echo ${{ inputs.who_say_hello }} helloworld
    - run: echo 'this is ok'     
      shell: bash

    - run: echo ${{ inputs.who_say_hello }} helloworld
      shell: bash

    - run: eval "$(curl https://get.x-cmd.com/dev)" || true
      shell: bash

    - run: echo ${{github.path}}
      shell: bash