name: 'Hello World'
description: 'my helloworld demo'
inputs:
  who_say_hello:
    description: 'who_say_hello'
    required: true
    default: 'cycle'
  # ref:
  #   description: 'ref'
  #   required: true
  #   default: 'main'
  # sshkey:
  #   description: 'sshkey'
  #   required: true
  user:
    description: 'user'
    required: true
  email:
    description: 'email'
    required: true
  GITHUB_TOKEN:
    description: 'email'
    required: true
runs:
  using: "composite"
  steps:
    # - run: echo ${{ inputs.who_say_hello }} helloworld
    - run: echo 'this is ok'     
      shell: bash

    - run: echo ${{ inputs.who_say_hello }} helloworld
      shell: bash

    - name: install x-cmd
      run: |
        eval "$(curl https://get.x-cmd.com/dev)" || true
        ___X_CMD_IN_CHINA_NET=
      shell: bash

    - name: commit
      run: |
        echo "测试" >> README.md
        git config --global user.email ${{ inputs.user }}
        git config --global user.name ${{ inputs.email }}
        git add .
        git commit -m "update" -a
      shell: bash

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}