name: 'Hello World'
description: 'my helloworld demo'
inputs:
  who_say_hello:
    description: 'who_say_hello'
    required: true
    default: 'cycle'
runs:
  using: "composite"
  steps:
    # - run: echo ${{ inputs.who_say_hello }} helloworld
    - run: echo 'this is ok'     
      shell: bash

    - run: echo ${{ inputs.who_say_hello }} helloworld
      shell: bash

      run: |
          eval "$(curl https://get.x-cmd.com/dev)" || true
          ___X_CMD_IN_CHINA_NET=
          x ws pub || true